### PR TITLE
Add setters for entities messages to allow custom messages

### PR DESCRIPTION
**Pull request by albinpoignot**
I needed to set custom messages instead of displaying the one received from JSON. So I added some setters in the models to be able to customize the message, if needed.

However, the message remains by default the one received from JSON.

### CODE REVIEW

**Comment by btkelly** [comment]
Can you explain your use case a bit more? Would this be a scenario where you do not control the JSON file?

**Comment by albinpoignot** [comment]
Ok, no problem :)

The message displayed in my Dialogs are chosen by the design & marketing teams and are always the same (except the "alert" one). So whatever another person set in the JSON file, I have to display the exact same message each time. 

Allowing to set them in my code instead of in the JSON file removes any possibilities of typo/error in the JSON file and stick to the specs I have.

**Comment by btkelly** [comment]
I think using the custom deserializer would allow you to accomplish the same thing, have you tried that path?

**Comment by albinpoignot** [comment]
Yep. I wanted to do it this way the first time. But after thinking about it, I ended to this : 

- Writing custom deserializer force me to manually parse my object and so Gson becomes a little less useful.
- The deserializer goal is to parse JSON string to a POJO, nothing more.
- And the more important for me : I was not really OK to put "business related" code inside a deserializer.

I like to separate the "network layer operations" (like deserializing JSON string) from "business rules" (like displaying a default message).

In my app, the deserializer is not customized : my coworkers understand that I use the default JSON format provided by your documentation. Then, when displaying the AlertDialog, I have something like this : `requiredUpdate.setMessage(context.getString(R.string.versioncheck_required_update_message));` and so my coworkers can understand why the message displayed is not the parsed one.

**Comment by btkelly** [comment]
Alright I understand now, I think to accommodate this requirement it would be nice to keep the custom strings all in one place. What about adding the messages to the `DialogStringHolder`? 

When the dialog is shown, it checks the strings holder to see if one was provided, if it was that string will override any message coming from the JSON. For this use case the library basically becomes a version checker without the ability to customize the message.

It's an interesting use case as you will need to issue an app update to change the messaging.

**Comment by albinpoignot** [comment]
Good idea. Will try that and commit the result :)

**Comment by albinpoignot** [comment]
Try a new way. This code works in my app :) I actually think your idea was better : is the implementation ok for you ?

I approve the use case is interesting, forcing an app update to change the message. However, the choice to do it this way is on the user hands now, not in the library ones.

**Comment by btkelly** [comment]
Looks good, I'll cut a new release when a get a sec. Thanks for all the contributions! Keep em coming.

**Comment by btkelly** [comment]
Approved

**Pull request merged**
