### PR TITLE
Check for alerts before update

### LINKED ISSUE #65: Blocking alert not shown when user skips optional update
If there is a blocking alert and an optional version set, the user is presented with the optional update but can skip and continue using the app without ever seeing the alert.

### PR DESCRIPTION
**Pull request by kyhule**
This PR fixes #65. The optional update check was moved to be after the alert check. This satisfies the business logic of any blocking condition checks should take precedences over non-blocking checks.

### CODE REVIEW

**Comment by btkelly** [comment]
This does solve the issue posted but I'm wondering if we should add additional logic between blocking and non blocking alerts. My main concern is the case where you may need to show a blocking alert because the whole system is down. In this case even a required update would not be the correct action.

Thoughts on this order:

```
If blocking alert show
Else if required update show
Else if optional update show
Else if non blocking alert show
```

**Comment by kyhule** [comment]
@btkelly Yeah, I considered that but figured if the user updates to the latest and come back, they will get the blocking alert. My coworker and I went back and forth on would we rather the user be told to update and then see a blocking alert or for them to see a blocking alert and then come back later to see they have to update the app.  We figured that if the app is blocking due to system being down, at least they can go and update their app while they wait.

**Comment by btkelly** [comment]
I don't really have a strong opinion either way, I'm good with this. Just need to merge master and we should be set.

**Comment by jsibbold** [comment]
this looks good for now, Approved

**Comment by jsibbold** [comment]
Approved

**Comment by jsibbold** [comment]
Unapprove

**Comment by jsibbold** [comment]
looks like it's out of date with master

**Comment by kyhule** [comment]
Sorry about that. It's up to date now. Do you guys have an idea when you will cut a new release?

**Comment by jsibbold** [comment]
Approved

**Comment by btkelly** [comment]
I'll cut one right now

**Pull request merged**
